-- Majestic Roobee — the real catalogue.
--
-- Replaces the demo data migration 0002 seeded (tagged by 0007) with the live
-- product list from the client's catalogue: 188 products across 13 categories,
-- 198 sizes. Source: MajesticRoobee_Product_Catalog.xlsx (August 2026).
--
-- Deliberate choices, all editable in the admin afterwards:
--   * Photos are left empty — they are uploaded from Admin → Catalogue.
--   * Every size opens with the same stock at all three stores; real counts
--     are set per store in Admin → Inventory.
--   * The 90 products the catalogue has no copy for get an empty description
--     rather than invented copy.
--   * Scent family is no longer used, so it is stored empty.
--   * Everything ships live; drafts are a per-product toggle in the admin.

-- 1. Clear the demo records. Only rows tagged seeded=1 by 0007 are touched,
--    so anything the shop created itself survives.
DELETE FROM wishlists WHERE product_id IN (SELECT id FROM products WHERE seeded = 1);
DELETE FROM products WHERE seeded = 1;   -- variants -> stock cascade
DELETE FROM orders WHERE seeded = 1;     -- order_items / order_events cascade
DELETE FROM inquiries WHERE seeded = 1;  -- inquiry_messages cascade
DELETE FROM abandoned_checkouts WHERE seeded = 1;
DELETE FROM promos WHERE seeded = 1;
DELETE FROM campaigns WHERE seeded = 1;

-- 1b. FIRSTTRAIL is not demo data: the lead popup prints that code on screen and
--     /api/leads hands it out, so the row has to exist for the code to work at
--     checkout. Re-created as a real promo, with the demo redemption count reset.
INSERT INTO promos (code, kind, value, descr, scope, starts, ends, status, redemptions, seeded)
VALUES ('FIRSTTRAIL', 'pct', 10, '10% off first order (lead capture)', 'Storewide', 'Always on', '—', 'Active', 0, 0)
ON CONFLICT(code) DO NOTHING;

-- 1c. The announcement bar advertised QUEEN10, which has just been deleted. Only
--     rewritten while it still carries that demo line, so a message the shop has
--     written itself is never overwritten.
UPDATE settings SET value = json_set(value, '$.announcement',
  'Free Abuja delivery over ₦100,000 · Now serving Abuja, Lagos & Ibadan')
WHERE key = 'site' AND json_extract(value, '$.announcement') LIKE '%QUEEN10%';

-- 2. The real categories. Four of the demo ids carry over because they name the
--    same shelf; the rest are new.
INSERT INTO categories (id, label, sort) VALUES
  ('extrait', 'Extrait Perfumes', 1),
  ('designer', 'Designer Oils', 2),
  ('custom-oil', 'Custom Oils', 3),
  ('mist', 'Body Mists', 4),
  ('home', 'Home Fragrance', 5),
  ('deo', 'Deodorants', 6),
  ('care', 'Feminine Care', 7),
  ('massage', 'Massage Oils', 8),
  ('health', 'Health Drinks', 9),
  ('fragrance-set', 'Fragrance Sets', 10),
  ('mist-set', 'Body Mist Sets', 11),
  ('custom-oil-set', 'Custom Oil Sets', 12),
  ('gift-set', 'Gift Sets', 13)
ON CONFLICT(id) DO UPDATE SET label = excluded.label, sort = excluded.sort;

-- 3. 'sensual' and 'package' have no equivalent in the real catalogue. Move any
--    product the shop added under them onto the closest real category first, so
--    the foreign key holds, then retire them.
UPDATE products SET cat = 'extrait' WHERE cat = 'sensual';
UPDATE products SET cat = 'fragrance-set' WHERE cat = 'package';
DELETE FROM categories WHERE id IN ('sensual', 'package');

-- 4. The catalogue — 188 products.
--    Upserts, so re-running against a store that already holds one of these
--    (by slug) refreshes it rather than failing the migration. Where the two
--    disagree the catalogue wins on name and shelf, but never overwrites copy,
--    a photo or a draft flag the shop set itself.
INSERT INTO products (id, name, cat, gender, family, notes, descr, image_url, live) VALUES
  ('dewivy-bodymist', 'Dewivy bodymist', 'mist', 'Unisex', '', '', 'Awaken your senses with Dewivy, a floral body mist that captures the crisp, soft-toned magic of dawn. This green-fresh floral fragrance is a love letter to nature, blending watery greens with delicate florals to create a scent that is as refreshing as a deep breath of mountain air. It''s clean, sophisticated, and perfect for those who want to feel revitalized and naturally elegant all day long.', NULL, 1),
  ('exotic-kiss-bodymist', 'Exotic kiss bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('goldplum-bodymist', 'Goldplum bodymist', 'mist', 'Unisex', '', '', 'Goldplum Body mist is a juicy, mouth-watering fruity perfume made for women who love to smell irresistibly good from morning till night. A delicious blend of berries, vanilla, ripe peaches and creamy sandalwood that feels playful, feminine and addictive. It is fresh, sweet, and long-lasting. A true ladies'' bestseller.', NULL, 1),
  ('macho-bodymist', 'Macho bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('magicspell-bodymist', 'Magicspell bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('pheromona-bodymist', 'Pheromona bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('sisi-bodymist', 'Sisi bodymist', 'mist', 'Unisex', '', '', 'Sisi is your instant splash of happiness. It is a bright, refreshing citrus fragrance mist that keeps you smelling clean, fresh and confident for over 12 hours on the skin. A blend of mandarin, sweet orange, vanilla, magnolia and oud., It is light, sparkling, and addictively fresh.', NULL, 1),
  ('sugar-lips-bodymist', 'Sugar lips bodymist', 'mist', 'Unisex', '', '', 'Sugarlips Body Mist is a body mist that captures the playful essence of a sugar-coated dream. This is a "soft-toned" gourmand at its finest, never heavy, always inviting. Designed for the woman who loves to radiate warmth and sweetness. Sugarlips leaves a delicious trail that is as addictive as your favourite treat.', NULL, 1),
  ('tango-bodymist', 'Tango bodymist', 'mist', 'Unisex', '', '', 'Tango is a unisex appealing woody body mist that captures the soul of a moonlit dance. This is a soft-toned sultry scent, bold enough to be noticed, yet light enough to wear like a second skin. A mildly intense rich blend of sandalwood, vanilla, oud, leather, rum. It''s designed for the individual who moves with confidence and leaves a trail of mystery in their wake.', NULL, 1),
  ('tlc-bodymist', 'TLC bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('toke-bodymist', 'Toke bodymist', 'mist', 'Unisex', '', '', '', NULL, 1),
  ('body-mist-set-of-11', 'Body mist set of 11', 'mist-set', 'Unisex', '', '', '', NULL, 1),
  ('body-mist-set-of-6', 'Body mist set of 6', 'mist-set', 'Unisex', '', '', '', NULL, 1),
  ('2sexy2resist', '2sexy2resist', 'custom-oil', 'Unisex', '', '', '2SEXY2RESIST is a bold, irresistible fragrance made to turn heads and leave a lasting impression. A strong intense floral fragrance that evokes the strong embrace of love and intimacy, melting into the softness of skin on skin and fresh linen sheets. The fragrance that makes hearts beat faster, manners lost, stops time because the most beautiful moments are ignited once you wear this fragrance. Loved by thousands of women and a major staple for any lady who wants to increase the spark in her relationship. This fragrance is very heavy on benzoin, sandalwood, oud and vanilla.', NULL, 1),
  ('a-million-kisses', 'A million kisses', 'custom-oil', 'Unisex', '', '', 'From tuberose to bubblegum, orchids, aldehydes, lily of the valley, bergamot, and sandalwood—Million Kisses is pure magic in a bottle Expect to leave everyone around you completely consumed and utterly mesmerized. It''s lush, it''s heady, it''s unapologetically YOU. Warning: This is for QUEENS ONLY. Spray lavishly, strut boldly, and watch as random kisses, endless compliments, and unwavering admiration follow you. The dry-down? An undeniable 10/10. This fragrance screams, “I''m here, I''m staying, and I OWN this throne!”', NULL, 1),
  ('after-dark', 'After dark', 'custom-oil', 'Unisex', '', '', 'After Dark is a sweet, woody and a bit minty sensation. This fragrance steals your heart before you know it. A perfect blend of lemon, apple, clarysgae, ambroxan, cedarwood, patchouli, vetiver and vanilla. This luminous fragrance is enveloping. A woody oriental fresh unisex fragrance for people who want to tell unique stories with their smellgame.', NULL, 1),
  ('bad-character', 'Bad character', 'custom-oil', 'Unisex', '', '', 'Bad Character EDP is a sparkling floral fragrance. A blend of Turkish rose, bergamot, ylang-ylang and cedarwood. This zesty floral perfume ignites adventure, love, passion and meant for those days you want your aura to be felt before you''re seen.', NULL, 1),
  ('bgs02', 'BGS02', 'custom-oil', 'Unisex', '', '', 'BGS02 50ML Extrait Perfume is a long-lasting luxury fragrance with a soft floral heart and a warm woody-musky base for an elegant, unforgettable signature scent.', NULL, 1),
  ('boss-babe', 'Boss babe', 'custom-oil', 'Unisex', '', '', 'Boss Babe for Women is a sultry fragrance created for women who are not afraid to embody their feminity. It is sexy, flirty, juicy, succulent while being heavily sophisticated. That type of fragrance that gets you stares, opens conversation, and have every lady in the room, wondering what made you so special. Boss babe is a definite must have. It opens with sweet honey and sparkling citrus, melts into a juicy floral heart of cherry, tuberose, orange blossom and pear, and settles into a warm, addictive base of vanilla, tonka bean, sandalwood, amberwood and white musk.', NULL, 1),
  ('chapter-5', 'Chapter 5', 'custom-oil', 'Unisex', '', '', 'This floral bouquet, composed around May rose and jasmine, features bright citrus top notes. Aldehydes create a unique presence, while the smooth touch of bourbon vanilla yields an incredibly sensual sillage.', NULL, 1),
  ('cleopatra', 'Cleopatra', 'custom-oil', 'Unisex', '', '', 'Cleopatra Secrets is a custom hydro perfume. It blends powdery musk and floral aphrodisiacs into a sensual, long-lasting night perfume that clings beautifully to the skin. It is a stunning fragrance that is overwhelming & irresistible; a true symbol of femininity. It combines the magical essences of passion fruit, fresh flowers and precious woods. The woman who uses is radiant,dreamy and not afraid to embody her sensuality to the core. Non-alcoholic, feminine, and unforgettable. Most women vouch for this fragrance as a constant staple that increases the romance in their relationship due to the heavy dirty florals and pheromone materials in it. How to use: Spray on body and lingerie after a night shower. Best paired with the Bikini Package.', NULL, 1),
  ('dangerous', 'Dangerous', 'custom-oil', 'Unisex', '', '', 'Dangerous is a soft-toned floral masterpiece of tension and release. This Natural Extrait is high concentration luxury in its purest form, designed for the woman who is effortlessly captivating and entirely unforgettable. It is the scent of mystery, a whisper of power that lingers on the skin long after you''ve left the room.', NULL, 1),
  ('dominance', 'Dominance', 'custom-oil', 'Unisex', '', '', 'Dominance is a Leathery Extrait de Parfum for Men. It is a modern, niche luxury fragrance created for confident, sophisticated individuals. Featuring a fresh-leather opening with a bold, refined woody build, this powerful unisex perfume delivers intense performance, strong projection and over 24 hours of long-lasting wear. A best seller fragrance for men of all ages.', NULL, 1),
  ('dynasty', 'Dynasty', 'custom-oil', 'Unisex', '', '', 'Dynasty is a bold, smoky-spicy, zesty custom oil made for men who command attention without saying a word. It has powerful projection, unforgettable silage and an ultra-long-lasting trail that keeps working long after you leave the room. Dynasty smells dominant, feels elite and leaves a legacy. If you do not like to take centre stage, avoid this fragrance because it is an announcer.', NULL, 1),
  ('erotica', 'Erotica', 'custom-oil', 'Unisex', '', '', 'EROTICA is a sensual custom-blend fragrant oil, designed for one thing only. Naughty escapades. This is for when you want to drive down the wild side without any inhibitions. Erotica is made from narcissus dirty florals and juicy pomegranate, labdanum and sandalwood. It screams eat me without leaving any crumbs. Lover gang, grab this.', NULL, 1),
  ('essence-of-love', 'Essence of love', 'custom-oil', 'Unisex', '', '', 'Essence of Love is a soft spicy, aquatic,musky unisex fragrance. The notes are lavender, pineapple, pink pepper, patchouli and leather .this aromatic fresh woody perfume is a mega heart stealer. Ready to steal the show? Turn conversations around? Have everyone including strangers want to snuggle up to you, ready to be extremely desired? Essence of love is strictly made to sweep hearts off their feet. By the time they realize what has happened, they are already helplessly in love with you. This is the fragrance you wear to important events, important locations where you want high quality conversations yet in an unprofessional settings. This fragrance is a game changer for ladies. It is also massively loved by men who want to get yes as an answer.', NULL, 1),
  ('flames', 'Flames', 'custom-oil', 'Unisex', '', '', '', NULL, 1),
  ('good-girl-carolina', 'Good girl carolina', 'custom-oil', 'Unisex', '', '', 'Good Girl Carolina is a sensual ambery floral perfume for women that blends bright jasmine and creamy tuberose with warm and sweet roasted tonka bean. Almond adds softness while cocoa deepens the scent, creating a modern, addictive blend with hints of vanilla and subtle woody warmth.', NULL, 1),
  ('high-voltage', 'High voltage', 'custom-oil', 'Unisex', '', '', 'High Voltage eau de parfum with notes of passionfruit, cherry, orchid, hibiscus, agarwood, musk and amber. This perfume is wild, sexy, addictive and totally irresistible. A pheromone infused perfume that drives people wild with desire, passion and emotions. Long lasting, addictive, the ladies cannot get enough of this perfume. A definite compliment bringer. Perfect for everyday wear, date nights, office wear and very versatile.', NULL, 1),
  ('intenso', 'Intenso', 'custom-oil', 'Unisex', '', '', 'Intenso is a bold yet smooth luxury fragrance crafted for those who love depth, confidence, and lasting impression. Rich, sensual notes blend seamlessly into a long lasting perfume oil that sits beautifully on the skin and evolves all day. It is an all manly Eau De Parfum mixing in woody essences with soft floral- oriental smells that brings out the best of both sides. While the wood based fragrances are mostly reserved for a strong rugged yet passionate outlook, the use of soft flower bases brings out the charm allowing man to connect with both the caring and carefree sides. It is an intense electrifying perfume to freshen up your senses. The top layers of this perfume include the sweet smelling lavender while the heart notes revolt with pear, ambrette and iris. Moving on towards the end, you experience the cedarwood and vetiver. Shop intense, a premium, long-lasting perfume made for statement makers and unforgettable moments.', NULL, 1),
  ('invictus', 'Invictus', 'custom-oil', 'Unisex', '', '', '', NULL, 1),
  ('kemistry', 'Kemistry', 'custom-oil', 'Unisex', '', '', 'Unlock a scent that reacts uniquely to your skin with Kemistry. This soft-toned custom oil isn''t just a fragrance; it''s a personal signature. Formulated to adapt to your body''s natural chemistry, Kemistry creates a bespoke aroma that is impossible to replicate. It''s sophisticated, intimate, and deeply magnetic, designed for those who want to be remembered long after they''ve left the room.', NULL, 1),
  ('kill-me-softly', 'Kill me softly', 'custom-oil', 'Unisex', '', '', 'Kill Me Softly is a powerful unisex fragrance created to leave a lasting impression from the very first spray. Warm, glowing and quietly seductive with florals and juicy sweetness for a trail that turns heads and lingers beautifully. This fragrance is an overdose of juicy sweetness. The most beautiful part is that it lasts over two days.', NULL, 1),
  ('kiss-me-deep', 'Kiss me deep', 'custom-oil', 'Unisex', '', '', 'Kiss Me Deep is an enchanting fruity floral fragrance. This irresistible elixir casts a spell of timeless allure, drawing you into a world of magnetic charm and subtle seduction.', NULL, 1),
  ('lick-me-up', 'Lick me up', 'custom-oil', 'Unisex', '', '', 'Lick me up is a pheromone-infused Hydro Perfume made to tempt and tease. A seductive blend of juicy berries, wildflowers, warm resins, and exotic spices that awakens desire and draws them irresistibly closer. Smell edible. Feel powerful. Add to cart.', NULL, 1),
  ('love-breeze-02', 'Love breeze 02', 'custom-oil', 'Unisex', '', '', '', NULL, 1),
  ('love-spell', 'Love spell', 'custom-oil', 'Unisex', '', '', 'With carefully selected notes that balance freshness, warmth, and sensual depth, Lush Life Fragrance Extract enhances your presence effortlessly, whether for everyday wear or special occasions. Just a small application unveils a long-lasting fragrance experience that evolves gracefully throughout the day. Fragrance Profile: Top Notes: Fresh and vibrant accents that awaken the senses Heart Notes: Soft, floral or aromatic layers that add character Base Notes: Deep, warm undertones for a lasting signature Key Features: Highly concentrated for long-lasting wear Smooth, rich scent with a luxurious finish Suitable for both day and evening use Crafted for individuals who value elegance', NULL, 1),
  ('made-for-romance', 'Made for romance', 'custom-oil', 'Unisex', '', '', 'Made for Romance is a hauntingly romantic scent that is composed using calm aquatic notes. A combo of citrus, blackcurrant, lily, may rose, jasmine, vetiver, orris , peach and raspberry. This fragrance is the bomb. Strictly made for when you want all caution to be thrown to the wind. First it creates an urgency in the brain, then it wraps around you, drawing you into every minute and making you never ever wanting those moments too end. A fragrance that can get your skin sniffed for hundreds of times by anyone near you. The people who understand the power of this fragrance already ensures it never misses in their collection. A must-have. It is Perfect for everyday love stories and intimate moments, this long-lasting women''s perfume delivers a clean, romantic scent trail that feels light, feminine and unforgettable. Shop Made for Romance today and fall into a fresh, elegant fragrance made to be remembered.', NULL, 1),
  ('miz-pheromone', 'Miz pheromone', 'custom-oil', 'Unisex', '', '', 'Some fragrances are worn. Mz Pheromone is experienced. Soft white florals, creamy musk, delicate powder, fresh green notes, and warm sensual woods come together to create a fragrance that feels intimate, confident, and undeniably captivating. Rich cashmeran wraps around tuberose and jasmine, while vanilla, petitgrain, benzoin, and a touch of labdanum leave behind a warm, addictive trail that lingers beautifully on the skin. Mz Pheromone was created for the woman who isn''t afraid to embrace her femininity and sensuality. It is bold, elegant, and unforgettable. Perfect for date nights, anniversaries, romantic evenings, and every moment you want to leave a lasting impression. The projection is beautiful, the longevity is exceptional, and the scent has a way of drawing people closer, making every hug last a little longer and every conversation a little more memorable. Notes: Cashmeran • Tuberose • Jasmine • Vanilla • Benzoin.', NULL, 1),
  ('molecule-05', 'Molecule 05', 'custom-oil', 'Unisex', '', '', '', NULL, 1),
  ('money-bag', 'Money bag', 'custom-oil', 'Unisex', '', '', 'It is unisex, powerful, intriguing and leaves a very rich impression. This isn''t just fragrance it is respect and status in a bottle. Wear this woody-leathery sensation when you want to smell like the money you''ll attract. The trail and projection of moneybag scream wealth only.', NULL, 1),
  ('nutty', 'Nutty', 'custom-oil', 'Unisex', '', '', '', NULL, 1),
  ('osk-limited', 'Osk limited', 'custom-oil', 'Unisex', '', '', 'OSK is beast mode in a bottle. The fragrance that one sniff drives you wild with thoughts, passions and romance. OSK is powerfully seductive. A unisex sensation that makes people only think of keeping you for permanent purposes. A blend of grapefruit, agarwood, sandalwood and musk. This is a steady banger. It does not seat for long on our shelves.', NULL, 1),
  ('sauce-queen', 'Sauce queen', 'custom-oil', 'Unisex', '', '', 'Sauce Queen is a soft, irresistible floral-musky fresh gourmand fragrance designed to spark instant attraction and endless compliments. This long-lasting women''s perfume gently fills the room when you arrive and lingers beautifully long after you leave. The sweetness of this perfume cannot be compared to any thing. You may want to avoid this if getting excess compliments is not your thing.', NULL, 1),
  ('secrets-stilettos', 'Secrets & stilettos', 'custom-oil', 'Unisex', '', '', 'Some fragrances smell beautiful. Secrets & Stilettos leaves people completely intrigued. This chypre floral masterpiece is white floral, warm, spicy, sweet, balsamic, aromatic, earthy, and woody. The richness of ylang-ylang, gardenia, and patchouli melts effortlessly into benzoin, sandalwood, and vanilla, creating a scent that is luxurious, mysterious, and impossible to forget. This is for the woman who knows exactly who she is. The woman who can walk from the boardroom to the bedroom without changing her energy. Every room feels brighter when she walks in because her confidence arrives before she speaks. Secrets & Stilettos doesn''t just earn compliments. It starts conversations. People remember you, wonder what you''re wearing, and somehow can never quite figure it out. That mystery is exactly what makes it unforgettable. Notes: Ylang-Ylang • Gardenia • Patchouli • Benzoin • Petitgrain, Sandalwood • Vanilla.', NULL, 1),
  ('sweet-sin', 'Sweet sin', 'custom-oil', 'Unisex', '', '', 'Sweet Sin is the fresh, clean fragrance everyone wants to stay close to. It is a fresh and modern fragrance for men. It opens with captivating notes of Mediterranean neroli and golden apple, followed by a heart of lavender, fir, and black pepper. The base is composed of vanilla, patchouli, and musk, leaving a memorable and long-lasting impression. An ultra-refreshing unisex scent with airy citrus, soft aquatic notes and a smooth musky-amber finish that feels crisp, classy and irresistibly modern. It''s bougie, and perfect for work, everyday wear and scent layering. Smell fresh. Look polished. Feel unforgettable.', NULL, 1),
  ('under-his-skin', 'Under his skin', 'custom-oil', 'Unisex', '', '', 'Under His Skin is a sweet, intimate fragrance designed to evoke the feeling of bare skin, It offers a soft, lingering scent suitable for daily wear and has moderate longevity. Vibe: Intimate, cozy, and alluring.', NULL, 1),
  ('very-sexy-you', 'Very sexy you', 'custom-oil', 'Unisex', '', '', 'Very Sexy is that chypre floral fragrance you didn''t see coming.This fragrance is chic, feminine and juicy. It is quietly seductive, beautifully soft, this is your natural sexy in a bottle. Perfect for daytime, events, hangouts and for date nights, add a touch of essence of love and have them gush over you all night.', NULL, 1),
  ('assasination-box-1', 'Assasination box 1', 'custom-oil-set', 'Unisex', '', '', '', NULL, 1),
  ('assasination-box-2', 'Assasination box 2', 'custom-oil-set', 'Unisex', '', '', '', NULL, 1),
  ('dr-teals-coconut', 'Dr teals coconut', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('dr-teals-elderberry', 'Dr teals Elderberry', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('dr-teals-energy-spray', 'Dr Teals energy spray', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('dr-teals-eucalyptus', 'Dr teals Eucalyptus', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('dr-teals-lavender', 'Dr teals lavender', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('dr-teals-rose-milk', 'Dr teals Rose & milk', 'deo', 'Unisex', '', '', 'Experience the perfect harmony of wellness and freshness with Dr Teals Coconut Deodorant. This soft-toned, unisex essential is crafted for those who want high-performance protection without the harsh chemicals. Infused with the soothing essence of coconut and skin-loving minerals, it keeps you feeling dry, confident, and smelling like a coastal getaway. It''s not just a deodorant; it''s a daily ritual of self-care that respects your body''s natural rhythm.', NULL, 1),
  ('5th-avenue', '5th avenue', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('addictive-ambergris', 'Addictive ambergris', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('afternoon-swim', 'Afternoon swim', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('amouage-decision', 'Amouage decision', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('amouage-epicman', 'Amouage epicman', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('amouage-existence', 'Amouage existence', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('amouage-outlands', 'Amouage outlands', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('amouage-portrayal', 'Amouage portrayal', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('ani-nishane', 'Ani Nishane', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('baccarat-rogue', 'Baccarat rogue', 'designer', 'Unisex', '', '', 'Baccarat Rouge 540 by Maison Francis Kurkdjian is one such fragrance that instantly leaves an indelible impression. Known for its radiant, amber signature, this perfume evokes a mysterious and addictive olfactory experience.', NULL, 1),
  ('baronda-massamoto', 'Baronda Massamoto', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('blue-talisman', 'Blue talisman', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('cool-water-women', 'Cool water women', 'designer', 'Unisex', '', '', 'Cool Water Woman is a Fresh Aquatic Perfume for Women by Davidoff is a soft, romantic and refreshing fragrance wrapped in calming ocean-inspired notes. Sparkling citrus, melon and water florals melt into delicate rose and jasmine, then settle into a smooth, feminine base of sandalwood, vetiver and soft fruits. Shop Cool Water Woman now and experience a clean, long-lasting women''s perfume that feels light, elegant and beautifully unforgettable. It''s perfect for everyday freshness and effortless charm.', NULL, 1),
  ('couture-oud', 'Couture oud', 'designer', 'Unisex', '', '', 'Oud Couture is a heavy oriental floral fragrance . Turkish rose and agarwood has never been better paired. This fragrance has people on a chokehold. Lasts over 24 hours. Sticks on you everywhere you go, changing narratives, opening doors, gliding with pride in every step you take. A major keeper.', NULL, 1),
  ('creed-carmina', 'Creed Carmina', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('decadence', 'Decadence', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('dior-sauvage', 'Dior sauvage', 'designer', 'Unisex', '', '', 'Dior Sauvage Designer Fragrance Oil delivers a fresh, spicy and irresistibly smooth scent that feels clean, confident and effortlessly seductive. We''ve captured the raw, masculine spirit of this cult classic and transformed it into a luxurious, alcohol-free oil. It''s the scent you love. It is crisp, noble, and fierce but with a softer, skin-hugging finish that lasts significantly longer than a traditional spray. Cool bergamot meets woody ambroxan in a dance of pure sophistication.', NULL, 1),
  ('fahrenheit', 'Fahrenheit', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('gucci-guilty-men', 'Gucci guilty men', 'designer', 'Unisex', '', '', 'Gucci Guilty Men is boldly masculine, effortlessly smooth and a scent for the rule-breaker. Embrace the essence of modern charisma with our Gucci Guilty Men inspired fragrance oil. This is the scent of freedom and individuality, reimagined in a luxurious, soft-toned oil. It''s designed for the man who is unapologetically himself, strong, mysterious, and always memorable. Top notes are Juniper, Lavender and Lemon; middle notes are Orange Blossom, Nutmeg and Spanish Labdanum; base notes are Dry Wood, Patchouli and Musk.', NULL, 1),
  ('gyan', 'Gyan', 'designer', 'Unisex', '', '', 'Embark on a journey of profound elegance with Gyan. This soft-toned designer fragrance oil is a tribute to the "divine wisdom" of the East, capturing a sophisticated balance between nocturnal shadows and starlit clarity. Concentrated and alcohol-free, it is designed for the modern connoisseur who seeks a scent that is both calming and commanding. Gyan doesn''t just scent the skin; it drapes it in a rich, velvety mystery.', NULL, 1),
  ('hibiscus-mahajad', 'Hibiscus mahajad', 'designer', 'Unisex', '', '', 'Inspired by tasting an infusion of hibiscus petals in the heart of a gemstone market, Hibiscus Majahad is a flamboyant, shimmering creation that glows with ruby red rose, crushed pomegranate and crystal clean mint, warmed by vanilla and amber.', NULL, 1),
  ('kutay-unique-luxury', 'Kutay unique luxury', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('limelight', 'Limelight', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('orage-lv', 'Orage Lv', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('oud-couture', 'Oud couture', 'designer', 'Unisex', '', '', 'Oud Couture is a heavy oriental floral fragrance . Turkish rose and agarwood has never been better paired. This fragrance has people on a chokehold. Lasts over 24 hours. Sticks on you everywhere you go, changing narratives, opening doors, gliding with pride in every step you take. A major keeper.', NULL, 1),
  ('oud-ispahan', 'Oud ispahan', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('oud-maracuja', 'Oud Maracuja', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('oud-satin-mood', 'Oud satin Mood', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('pacific-chill', 'Pacific chill', 'designer', 'Unisex', '', '', 'Pacific Chill is a fresh and uplifting fragrance inspired by the calm energy of the Pacific coast. Bright citrus, mint, and blackcurrant blend with aromatic herbs and a soft fruity base, creating a clean, modern scent that feels effortlessly elegant and refreshing.', NULL, 1),
  ('rich-leather', 'Rich leather', 'designer', 'Unisex', '', '', 'Rich Leather is a Luxury unique leathery oriental Woody Extrait Perfume is a powerful yet refined fragrance made for important meetings, special events and confident first impressions. Deep leather wrapped in smooth woody notes, spicy saffron, black pepper and ylang-ylang creates a unique, long-lasting scent that speaks success from the very first whiff. The dry down of agarwood, castoreum and patchouli seals the deal. This is like nothing you have ever experienced. Distinct, sharp, unforgettable.', NULL, 1),
  ('scandal-jpg', 'Scandal jpg', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('seminalis-orto-parisi', 'Seminalis orto parisi', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('si-armani', 'Si Armani', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('sugar-baby', 'Sugar baby', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('sugar-leather', 'Sugar leather', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('sun-song', 'Sun song', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('tygar', 'Tygar', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('vanilla-powder', 'Vanilla powder', 'designer', 'Unisex', '', '', '', NULL, 1),
  ('2sexy2resist-edp', '2sexy2resist EDP', 'extrait', 'Unisex', '', '', '2sexy2resist EDP is a bold, irresistible fragrance made to turn heads and leave a lasting impression. A strong intense floral fragrance that evokes the strong embrace of love and intimacy, melting into the softness of skin on skin and fresh linen sheets. The fragrance that makes hearts beat faster, manners lost, stops time because the most beautiful moments are ignited once you wear this fragrance. Loved by thousands of women and a major staple for any lady who wants to increase the spark in her relationship.', NULL, 1),
  ('b17', 'B17', 'extrait', 'Unisex', '', '', 'B17 is a smooth, modern eau de parfum that melts into your skin and leaves you wanting for more. An explosion of lavender, jasmine, vanilla and sandalwood.', NULL, 1),
  ('b18', 'B18', 'extrait', 'Unisex', '', '', 'B18 Eau de Parfum is a clean, modern fragrance with soft florals, gentle aromatics and a creamy woody-musky base for a long-lasting, elegant signature scent.', NULL, 1),
  ('b21', 'B21', 'extrait', 'Unisex', '', '', 'B21 Eau de Parfum is a clean, modern unisex fragrance with soft florals, gentle aromatics and a creamy woody-musky base for an elegant, long-lasting signature scent. B21 is a smooth, modern fragrance designed to melt into your skin and leave a gentle, confident trail that feels fresh, polished and quietly irresistible. It is Easy to wear, easy to love, and perfect for every day.', NULL, 1),
  ('b23', 'B23', 'extrait', 'Unisex', '', '', 'B23 is a smooth, modern eau de parfum designed to sit effortlessly on your skin and leave a calm, confident trail wherever you go. It is a clean, modern unisex fragrance with soft florals, gentle aromatics and a creamy woody musky base for an elegant, long-lasting signature scent.', NULL, 1),
  ('b24', 'B24', 'extrait', 'Unisex', '', '', 'B24 Eau de Parfum is a sweet amber gourmand scent that screams lick me up. A sexy edible fragrance that,makes you almost get licked up. A creamy delicious lactonic fragrance with a blend of caramel, sandalwood, toffee, vanilla and oud.', NULL, 1),
  ('b25', 'B25', 'extrait', 'Unisex', '', '', 'B25 is a soft yet confident everyday fragrance designed to sit beautifully on the skin and leave a calm, unforgettable trail. A fresh citrusy woody eau de parfum for clean conscious individuals. Easy to spray yet lingers all day.Effortless, modern and easy to love... this is the kind of scent that feels right from the first spray.', NULL, 1),
  ('b27', 'B27', 'extrait', 'Unisex', '', '', 'B27 Eau de Parfum is a clean, modern unisex fragrance with soft florals, gentle aromatics and a creamy woody-musky base for an elegant, long-lasting scent. It is a smooth, everyday luxury fragrance designed to sit beautifully on your skin and leave a clean, confident trail that never feels loud.', NULL, 1),
  ('bare-secrets', 'Bare secrets', 'extrait', 'Unisex', '', '', 'Bare Secrets is a sensual sweet floral fragrance that doesn''t scream for attention but somehow gets it anyway. Soft musks, delicate florals, and clean notes melt into your skin instead of sitting on top of it giving you something personal and intimate rather than overpowering. You need this if you''re the woman who''s tired of perfumes that announce themselves before you even walk in. If you love the kind of compliments that come with "you smell so good, what is that?" whispered close, not shouted across the room. This one lets people get close enough to actually notice you.', NULL, 1),
  ('bare-skin', 'Bare skin', 'extrait', 'Unisex', '', '', 'Some fragrances make an impression. Bare Skin creates an obsession. The first spray is impossible to predict. Musky, mossy, metallic, earthy, and wrapped in a sharp tropical freshness, it unfolds into something deeply sensual and incredibly intriguing. Bright mandarin meets the warmth of saffron and caramel before rose, precious woods, vanilla, and oakmoss create a scent that feels intimate, magnetic, and unforgettable. Bare Skin was made for moments that deserve to be remembered. Romantic dinners, special nights, quiet conversations that turn into unforgettable memories. It has the kind of chemistry that keeps people leaning in for one more hug, one more compliment, one more excuse to stay close. If you''re not ready to be consumed!!! Avoid this Notes: Mandarin • Saffron • Caramel • Rose • Woods • Vanilla • Oakmoss.', NULL, 1),
  ('breaking-rules', 'Breaking rules', 'extrait', 'Unisex', '', '', 'There is a reason women keep coming back to Breaking rules Fresh, aromatic, tropical, citrusy, lightly spicy, and wrapped in a delicious fruity sweetness, this is the kind of fragrance that instantly lifts your mood. It opens with juicy passion fruit and cherry before settling into the richness of oak and agarwood, leaving behind a sweet, refreshing trail that is impossible to ignore. Breaking is playful, feminine, and incredibly addictive. It is the perfect fragrance for date nights, weekend outings, vacations, and every moment you want to smell effortlessly attractive. Sweet without being overwhelming and refreshing from the first spray to the last, this is one of those fragrances you''ll never get tired of wearing. Notes: Passion Fruit • Cherry • Oak • Agarwood.', NULL, 1),
  ('honey-trap', 'Honey trap', 'extrait', 'Unisex', '', '', 'Honeytrap carries a secret you can almost taste at each spray. A blend of caramel, white chocolate, almonds, vanilla, brown sugar, and praline into a light, irresistible fragrance. This gourmand-lactonic perfume does not whisper. It snatches hearts, forcing them to bury their nose deep into your skin, licking you up all the way and randomly spoiling you with compliments. This fragrance could make you to literally chew yourself up. Be warned!!!. Perfect for intimate moments, romantic escapes, days you want to make people drool over you for good. Add to cart instantly. This is not your regular.', NULL, 1),
  ('ijele', 'Ijele', 'extrait', 'Unisex', '', '', 'IJELE Extrait Perfume is a beautifully intense extrait perfume created to sit close to your skin and leave a slow, unforgettable trail. Smooth, comforting and softly seductive, this is a scent that feels personal, confident and effortlessly elegant from the first spray. Strictly made for those who love the spotlight. A deep dirty floral fragrance, decadent enough to have everyone whispering your name and asking what''s the sauce. Ijele is a niche masterpiece.', NULL, 1),
  ('lavida-loca', 'Lavida loca', 'extrait', 'Unisex', '', '', 'Lavida Loca is a deliciously sweet gourmand fragrance wrapped in soft oriental notes that melts into your skin and lingers beautifully all day. Its a best-selling ladies'' perfume for women who love to stand out effortlessly. Want to be licked up? This does this. Wear this and you will have to keep saying no to the opposite gender. This is a major man eater seduction fragrance. A weapon for ladies that know.', NULL, 1),
  ('little-miss-temptation', 'Little miss temptation', 'extrait', 'Unisex', '', '', 'LITTLE miss temptation Extrait Perfume is a fragrance of soft life, romance, and effortless femininity. This wild juicy-bubble-gum explosion will have you smelling like what needs to be eaten up in real time. A dreamy blend of berries, cinnamon, yellow mandarin, jasmine, and patchouli that turns heads gently and leaves a beautiful, girly aura behind. It is perfect for brides, date nights, romantic dinners, or cozy luxury days. If you''re stepping into your soft-girl era, this is your fragrance.', NULL, 1),
  ('lush-life', 'Lush life', 'extrait', 'Unisex', '', '', 'With carefully selected notes that balance freshness, warmth, and sensual depth, Lush Life Fragrance Extract enhances your presence effortlessly, whether for everyday wear or special occasions. Just a small application unveils a long-lasting fragrance experience that evolves gracefully throughout the day. Fragrance Profile: Top Notes: Fresh and vibrant accents that awaken the senses Heart Notes: Soft, floral or aromatic layers that add character Base Notes: Deep, warm undertones for a lasting signature Key Features: Highly concentrated for long-lasting wear Smooth, rich scent with a luxurious finish Suitable for both day and evening use Crafted for individuals who value elegance.', NULL, 1),
  ('mind-games', 'Mind games', 'extrait', 'Unisex', '', '', 'Mind Game, an Extrait de Parfum designed for those who play to win. This is the pinnacle of twisted, intriguing intensity; a fragrance that combines high-concentration power with a smooth, velvety finish. This fragrance is a mind twister that gets people crawling for more. You''ll never imagine all the ways this fragrance gets to clutch at your heart, sweep you off your feet and effortlessly makes you fall in love completely with every whiff. A super blend of grapefruit, tangerine, rose, opopanax . you miss this, you truly missed a gem.', NULL, 1),
  ('opulent-pink-box', 'Opulent pink box', 'extrait', 'Unisex', '', '', 'A variety box with four variants of fragrances. Unveil a world of rosy luxury with the Opulent Pink Box. This curated gift package is a love letter to the modern woman, bringing together our most enchanting, soft-toned fragrances in one breathtaking collection. From powdery florals to sun-kissed sweetness, each scent is a masterclass in elegance, designed to make her feel as radiant as she looks.', NULL, 1),
  ('peak-of-passion', 'Peak of passion', 'extrait', 'Unisex', '', '', '', NULL, 1),
  ('pulze', 'Pulze', 'extrait', 'Unisex', '', '', '', NULL, 1),
  ('raw', 'Raw', 'extrait', 'Unisex', '', '', '', NULL, 1),
  ('rich-tension', 'Rich tension', 'extrait', 'Unisex', '', '', 'Rich Tension Extrait de Perfume is the invisible pull that makes people lean in, without even realising. It is a clean, non-toxic luxury perfume crafted with lavender absolute, petitgrain, lime, galbanum, clary sage, olibanum and labdanum. This unisex perfume is bold, complex and dangerously addictive. Smells powerful. Feels expensive. Leaves tension in the air in every room you step into.', NULL, 1),
  ('risky-fire', 'Risky fire', 'extrait', 'Unisex', '', '', '', NULL, 1),
  ('secret-flame', 'Secret flame', 'extrait', 'Unisex', '', '', 'Secret Flame, a natural extrait that defines soft-toned seduction. This isn''t a roaring fire; it''s the mesmerizing warmth of a glowing ember. Crafted with the highest concentration of botanical ingredients, Secret Flame is designed to meld with your skin''s natural chemistry, creating a magnetic, sophisticated aura that feels like a beautiful secret shared between you and your skin.', NULL, 1),
  ('sensuality-burst', 'Sensuality burst', 'extrait', 'Unisex', '', '', 'Sensuality Burst is seductive fragrance designed to evoke deep desires and provide a lingering, intimate aroma. It is a musky floral scent designed to create a memorable, and alluring impression. This fragrant oil is designed to melt into your skin and release a warm, intimate trail that quietly turns heads. Smooth, comforting and deeply seductive. This is your soft-power scent.', NULL, 1),
  ('sexy-time', 'Sexy time', 'extrait', 'Unisex', '', '', 'Sexy Time is a smoky fresh, seductive eau de parfum with juicy fruits, woody oriental notes and a warm vanilla musky base for an irresistible everyday signature scent.', NULL, 1),
  ('slow-k-ller', 'Slow k!ller', 'extrait', 'Unisex', '', '', 'Slow Killer is the fragrance they warned you about. Woody, spicy, floral, sweet, citrusy, ambery, and softly powdery, it has a way of completely mesmerizing everyone who experiences it. Orange blossom and jasmine open the fragrance with effortless elegance before amber, sandalwood, and vanilla create a rich, addictive dry down with a juicy citrus twist that keeps you wanting another sniff. This is an iconic scent. It smells expensive during the day, becomes irresistible at night, and somehow gets even better as the hours go by. The projection is beautiful, the trail is unforgettable, and it never feels overpowering. It is one of those rare fragrances you can confidently blind buy and instantly fall in love with. Perfect for both women and men, Slow Killer is made for work, date nights, special occasions, and every season of the year. Notes: Orange Blossom • Jasmine • Amber • Sandalwood • Vanilla.', NULL, 1),
  ('snatched', 'Snatched', 'extrait', 'Unisex', '', '', 'SNATCHED is a custom Aqua perfume and the ultimate man-eater energy in a bottle. It is bold, magnetic, and unapologetically addictive. This limited-edition luxury perfume is made to steal attention, steal hearts and leave your name in someone''s mind long after you''ve gone. One spray and you''re centre stage, instantly. This floral woody gourmand creation fuses the juicy sweetness of fruit with the delicate freshness of blooming flowers, revealing an explosion ASSn of unfiltered joy and pure pleasure. At the heart of this perfume lies the sensuality of the gardenia flower, magnified by rich, woody nuances that quicken the pulse and stir the senses.Snatched is dangerously sexy, powerfully feminine and impossible to forget.', NULL, 1),
  ('stuck-on-me', 'Stuck on me', 'extrait', 'Unisex', '', '', 'Stuck on me is a romantic floral-fruity fragrance for women, featuring a blend of sweet strawberry, black currant, peony, and vanilla musk. It mainly consists of big, plump, juicy, sweet strawberries and hearty patchouli! A touch of Sweetness. It''s girly, gently seductive, and oh so pretty! It smells good enough to eat! This is sweetness overload. A top choice of people who love to smell like what needs to be eaten up. This fragrance is super long lasting, activates a rush of love hormones. Wear this when you want the opposite gender to forget time. A must-have for every woman.', NULL, 1),
  ('sweet-addiction', 'Sweet addiction', 'extrait', 'Unisex', '', '', 'Sweet Addiction is a heavy Floral Fragrance Oil for Women is a soft yet irresistible blend of juicy blood orange, golden honey and creamy gardenia that melts beautifully into your skin. This addictive, long-lasting women''s perfume oil keeps evolving throughout the day and layers perfectly with almost all MajesticRoobee body mists. A best seller.', NULL, 1),
  ('sweet-berry-pop', 'Sweet berry pop', 'extrait', 'Unisex', '', '', 'Sweet Berry Pop is a juicy seductive blend where playful sweetness meets a deep, smoldering intensity. This is captivating and impossible to resist. We''ve combined the flirtatious notes of ripe fruits with the sophisticated warmth of dark gourmands to create a custom oil that feels like a velvet embrace.', NULL, 1),
  ('sweet-trouble', 'Sweet trouble', 'extrait', 'Unisex', '', '', 'Sweet Trouble is one of those fragrances you don''t expect to fall in love with... until the very first spray. Fresh, sweet, green, ambery, fruity, lightly spicy, and beautifully aquatic, it is a scent that feels vibrant, feminine, and effortlessly captivating. Bright mandarin and juicy pear blend with fresh green nuances before melting into the richness of patchouli and smooth caramel, creating a fragrance that is both comforting and incredibly addictive. It is perfect for work, beautiful enough for evenings, and versatile enough to become a signature scent. Sweet Trouble is the kind of fragrance every woman should experience at least once because once you smell it, you''ll understand why so many women never want to let it go. Notes: Mandarin • Green Nuances • Pear • Patchouli • Caramel.', NULL, 1),
  ('terri-3', 'Terri 3', 'extrait', 'Unisex', '', '', 'Terri3 Extrait de Perfume is the most versatile fragrance your body silently craves but does not realize it until you spray it. Terri3 is a spell of massive confidence. This amber-musky fragrance,gives a feel-good, I can conquer the world vibes. A bold fusion of the highly priced ambrette seed oil, cashmere wood, violet leaf, mandarin, clary sage,vetiver and musk that grips the senses and boosts confidence instantly. Terri3 is Magnetic, addictive, and unforgettable. Terri3 isn''t just a fragrance ,it''s an aura, a mood, a game-changer.', NULL, 1),
  ('the-topic', 'The topic', 'extrait', 'Unisex', '', '', 'For the woman who never needs to announce her arrival. TOPIC is bold, spicy, woody, and deeply earthy. It opens with the freshness of bergamot and juniper, unfolds into warm cardamom and mysterious black rose, then melts into the rich depth of immortelle and smooth benzoin, creating an unforgettable scent trail that stays with you for hours. This is the fragrance you wear when you want your confidence to speak before you do. Powerful without being loud. Sophisticated without trying too hard. It naturally commands attention, earns respect, and leaves people wondering who just walked past. Its intense, long-lasting composition makes it the perfect companion for work, important meetings, formal occasions, and every moment you want to leave a lasting impression. It also layers beautifully with every fragrance inside the TAC Box, allowing you to create a smell game that is uniquely yours. Notes: Bergamot • Juniper • Cardamom • Black Rose • Immortelle • Benzoin.', NULL, 1),
  ('vanilla-explosion', 'Vanilla explosion', 'extrait', 'Unisex', '', '', 'Vanilla Explosion is a Rich Madagascar vanilla blend with warm benzoin and smooth labdanum to create something sophisticated, comforting, and shockingly long-lasting. You need this if you love smelling expensive without trying. If you want a scent that wraps around you like a warm hug and stays on your skin hours after you''ve forgotten you sprayed it. This is vanilla for grown women, elegant, not childish. Deep, not basic.', NULL, 1),
  ('walking-daydream', 'Walking daydream', 'extrait', 'Unisex', '', '', 'Walking Daydream Extrait Perfume is soft, luxurious, and quietly unforgettable. Peach, nectarine, black currant, iris, vanilla, tonka bean, and musk melt into a refined scent that blooms on your skin and turns heads effortlessly. This subtle floral blend is addictive, and beautifully you. The kind of perfume that brings back your sexiness, whispers your name and sends soft hugs and shivers down the spine with every whiff.', NULL, 1),
  ('wild-by-default', 'Wild by default', 'extrait', 'Unisex', '', '', 'Wild by Default Extrait Perfume is a seductive blend of myrrh, oakmoss, agarwood and violet leaf that opens sweet... then slowly pulls you in with an irresistible, addictive grip. Softens every edge. Melts every tension. This aromatic Fougere perfume is warm, intimate, and dangerously unforgettable. Wild by Default smells like comfort, feels like desire and stays like a memory. If you want to be remembered long after you''ve left the space, wear this.', NULL, 1),
  ('armpitox', 'Armpitox', 'care', 'Unisex', '', '', 'Your underarms deserve more than just a cover-up. Introducing Armpitox, the soft-toned detox treatment that purifies, brightens, and balances your most sensitive skin. Designed to bridge the gap between high-end skincare and daily hygiene, Armpitox draws out impurities and neutralizes odors at the source. It''s the essential "reset button" for a fresher, healthier, and more confident you.', NULL, 1),
  ('bikini-booster', 'Bikini booster', 'care', 'Unisex', '', '', 'The bikini booster is a natural water and aloe-based lubricant infused with pheromones combine moisturizing, skin-safe ingredients with scent-based additives designed to enhance attraction and arousal. It mimics the body''s natural moisture and maintains vaginal pH balance. It is also free from fragrance, petrochemicals, and parabens, including synthetic colours and flavours. Unlock a new level of confidence with the Bikini Booster. This soft-toned, high-performance serum is specifically formulated to rejuvenate and enhance your most delicate skin. Whether you''re looking to smooth texture, even out skin tone, or simply add a healthy glow, this booster acts as a daily shot of radiance for your bikini line, making intimate moments to be smooth, addictive and pleasurable.', NULL, 1),
  ('bikini-brightening-cream', 'Bikini brightening cream', 'care', 'Unisex', '', '', 'Reveal your most radiant skin with the Bikini Brightening Cream. Specifically designed for your most intimate and sensitive areas; from the bikini line to underarms, this soft-toned treatment targets hyperpigmentation and shadows with the precision of high-end facial skincare. It''s not just about correcting; it''s about nurturing your skin back to its natural, luminous glow.', NULL, 1),
  ('bikini-freshener-mist', 'Bikini freshener mist', 'care', 'Unisex', '', '', 'Confidence shouldn''t have a curfew. Meet Bikini Freshener, the ultimate soft-toned mist designed for your most delicate areas. Whether you''re heading to the beach, the gym, or a long date night, this feather-light deodorant spray provides an instant burst of cooling comfort and a clean, subtle scent that keeps you feeling petal-fresh and dry. It is designed to provide daily freshness, odor control, and comfort for the external intimate area. Formulated to be gentle, help maintain pH balance, reduce bad smelling sweat, and prevent irritation. It is free from alcohol and formulated with plant extracts. Elevate your intimate care routine with products that prioritize your well-being and confidence. Explore our range of bikini products for a refreshing experience.', NULL, 1),
  ('bikini-oil', 'Bikini oil', 'care', 'Unisex', '', '', 'Our Bikini Oil Refill is the soft-toned, eco-conscious way to ensure your skin never spends a day without its signature silkiness. Designed to perfectly top up your original glass bottle, this refill preserves your intimate skincare ritual while treading lighter on the planet. It''s the same liquid gold you love; nourishing, brightening, and soothing; bottled with the future in mind.', NULL, 1),
  ('bikini-oil-refill', 'Bikini oil refill', 'care', 'Unisex', '', '', 'Our Bikini Oil Refill is the soft-toned, eco-conscious way to ensure your skin never spends a day without its signature silkiness. Designed to perfectly top up your original glass bottle, this refill preserves your intimate skincare ritual while treading lighter on the planet. It''s the same liquid gold you love; nourishing, brightening, and soothing; bottled with the future in mind.', NULL, 1),
  ('bikini-package', 'Bikini package', 'care', 'Unisex', '', '', '', NULL, 1),
  ('bikini-wash', 'Bikini wash', 'care', 'Unisex', '', '', 'Bikini Wash is a bikini feminine was is free of harmful chemicals to give you a simple, non-toxic, pH balancing formula infused with kinds of natural extracts. no sulphates, dyes or fragrances. Made from pure plant ingredients, made from Aloe vera, essential oils and plant derived surfactants. Toxic intimate care products can throw your pH out of balance. Use the ph balance for women intimate wash to keep your sensitive area healthy, clean and fresh day after day without disrupting their natural pH balance. Easy to use. Simply apply 1-2 pumps on clean, dry palm and gently rub all over intimate area to cleanse. No douching. After cleansing, rinse off with water, pat dry and follow up immediately with up to 4 to 5 pumps of the bikini oil. Rub all over private part The bikini Wash is gentle by nature and fresh design for your premium feminine care.', NULL, 1),
  ('cranbiotic-gummies', 'Cranbiotic gummies', 'care', 'Unisex', '', '', 'Experience the natural power of cranberries in a convenient, delicious form with our cranbiotic gummies. It''s made to support freshness, comfort and intimate balance, promote urinary and gut health balance, these delicious concentrated cranberry extract gummies help you feel clean, confident and beautifully in tune with your body. Each gummy delivers the protective benefits of cranberries, rich in antioxidants that help prevent bacteria from adhering to the urinary tract lining. Beyond urinary health, the antioxidant properties of cranberries support a healthy immune system, making these gummies a powerhouse addition to your daily routine. Designed for convenience and enjoyment, our cranbiotic Gummies are free from artificial additives. They''re an easy and tasty way to stay proactive about your health. Rediscover the joy of wellness with the cranbiotic Gummies , your delicious daily partner for a healthy urinary tract, gut health and vibrant lifestyle.', NULL, 1),
  ('freshness-gummies', 'Freshness gummies', 'care', 'Unisex', '', '', '', NULL, 1),
  ('hello-fresh-pits', 'Hello fresh pits', 'care', 'Unisex', '', '', 'Hello Fresh Pits (Feminine Care & Deodorant). Wave goodbye to odours and say hello to freshness. Confidence starts with a clean slate. Hello Fresh Pits is our premium, soft-toned solution for all day freshness that actually cares for your skin. Designed specifically for the feminine silhouette, this isn''t just a deodorant; it''s a total body care essential. Whether it''s a high-intensity workout or a long day at the office, stay dry, smell divine, and feel effortlessly cool.', NULL, 1),
  ('spa-set', 'Spa set', 'care', 'Unisex', '', '', 'Why choose one when you can have it all? The Bikini Spa Set is a curated, soft-toned collection designed to transform your intimate skincare into a high-end spa experience. From exfoliation to deep hydration and brightening, this three-step system works in perfect harmony to ensure your bikini area is silky-smooth, even-toned, and irresistibly soft. It''s the ultimate investment in your body''s comfort and radiance.', NULL, 1),
  ('yummy-bikini-oil', 'Yummy bikini oil', 'care', 'Unisex', '', '', 'Yummypum bikini Oil is a pure, gentle, and deliciously fresh intimate oil. The ultimate glow-up for your most intimate skin. Reclaim your confidence with the yummypum bikini oil, a premium feminine care oil designed to nourish, soothe, and scent your delicate areas with soft-toned perfection. This isn''t just a treatment; it''s a daily ritual of self-love. Crafted with plant-based botanicals, Yummypum bikini oil ensures you feel fresh, smell fresh down there, hydrated, and irresistibly smooth from morning to night, increases your body''s natural lubrication even during intercourse, enhances and tones the vulva walls after post partum, increases your snap back confidence , shields you from mild infections, prevents shaving bumps and over all, helps you glide through all phases of womanhood with pride.', NULL, 1),
  ('yummy-bikini-wash', 'Yummy bikini wash', 'care', 'Unisex', '', '', 'The yummypum bikini feminine wash is free of harmful chemicals to bikini kinds of natural extracts. no sulphates, dyes or fragrances. Made from pure plant ingredients, made from Aloe vera, essential oils and plant derived surfactants. Toxic intimate care products can throw your pH out of balance. Use the ph balance for women intimate wash to keep your sensitive area healthy, clean and fresh day after day without disrupting their natural pH balance. Easy to use. Simply apply 1-2 pumps on clean, dry palm and gently rub all over intimate area to cleanse. No douching. After cleansing, rinse off with water, pat dry and follow up immediately with up to 4 to 5 pumps of the yummypum bikini oil. Rub all over private part Yummypum bikini Wash is gentle by nature and fresh by design for your premium feminine care.', NULL, 1),
  ('peach-pink-box', 'Peach & pink box', 'fragrance-set', 'Unisex', '', '', '', NULL, 1),
  ('peach-box', 'Peach box', 'fragrance-set', 'Unisex', '', '', 'A variety box with four fragrances. Step into a world of golden warmth with the Opulent Peach Box. This curated gift package is a tribute to soft-toned sophistication, blending the luscious sweetness of stone fruits with delicate, airy florals. Designed for the woman who radiates grace and sunshine, this collection is an invitation to experience luxury in its most inviting form. Opulent Peach Box is warm, velvety, and irresistibly chic. Your signature smellgame starts here.', NULL, 1),
  ('ultimate-queens-package', 'Ultimate queens package', 'fragrance-set', 'Unisex', '', '', '', NULL, 1),
  ('back-to-school-kit', 'Back to school kit', 'gift-set', 'Unisex', '', '', '', NULL, 1),
  ('noni-berry-drink', 'Noni berry drink', 'health', 'Unisex', '', '', '', NULL, 1),
  ('00-1-diffuser', '00.1 diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('00-1-roomspray', '00.1 roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('arabian-oud-roomspray', 'Arabian oud roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('bed-of-roses-diffuser', 'Bed of roses diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('before-sunrise-diffuser', 'Before sunrise diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('before-sunrise-roomspray', 'Before sunrise roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('blackberry-roomspray', 'Blackberry roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('boozy-diffuser', 'Boozy diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('bougie-candle', 'Bougie candle', 'home', 'Unisex', '', '', '', NULL, 1),
  ('car-diffuser', 'Car diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('cherry-blossom-diffuser', 'Cherry blossom diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('cherry-blossom-roomspray', 'Cherry blossom roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('choco-haven-candle', 'Choco haven candle', 'home', 'Unisex', '', '', '', NULL, 1),
  ('citrus-grove-diffuser', 'Citrus & grove diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('citrus-grove-roomspray', 'Citrus grove roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('daisy-diffuser', 'Daisy diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('daisy-roomspray', 'Daisy roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('fresh-dawn-diffuser', 'Fresh dawn diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('fresh-dawn-roomspray', 'Fresh dawn roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('frozen-mountain-diffuser', 'Frozen mountain diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('homecoming-diffuser', 'Homecoming diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('laundry-perfume-floral', 'Laundry perfume floral', 'home', 'Unisex', '', '', '', NULL, 1),
  ('laundry-perfume-woody', 'Laundry perfume woody', 'home', 'Unisex', '', '', '', NULL, 1),
  ('naughty-wild-candle', 'Naughty & wild candle', 'home', 'Unisex', '', '', '', NULL, 1),
  ('pine-sky-diffuser', 'Pine & sky diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('sacred-space-diffuser', 'Sacred space diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('sacred-space-roomspray', 'Sacred space roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('sips-roomspray', 'Sips roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('soft-corner-diffuser', 'Soft corner diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('soft-corner-roomspray', 'Soft corner roomspray', 'home', 'Unisex', '', '', '', NULL, 1),
  ('strawberry-cheesecake-candle', 'Strawberry cheesecake candle', 'home', 'Unisex', '', '', '', NULL, 1),
  ('sweet-berry-diffuser', 'Sweet berry diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('tangacitra-candle', 'Tangacitra candle', 'home', 'Unisex', '', '', 'Illuminate your sanctuary with Tangacitra, a candle designed to capture the vibrant energy of a Mediterranean citrus grove at sunset. This soft-toned home fragrance balances zesty brightness with a sophisticated, creamy finish. Whether you&#39;re hosting an intimate dinner or unwinding after a long day, Tangacitra sets a mood that is both invigorating and deeply comforting.', NULL, 1),
  ('wild-fig-diffuser', 'Wild fig diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('zanga-diffuser', 'Zanga diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('zingy-diffuser', 'Zingy diffuser', 'home', 'Unisex', '', '', '', NULL, 1),
  ('massage-oil-sensual', 'Massage oil sensual', 'massage', 'Unisex', '', '', '', NULL, 1),
  ('massage-oil-wild-emotion', 'Massage oil wild emotion', 'massage', 'Unisex', '', '', '', NULL, 1)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, cat = excluded.cat,
  descr = CASE WHEN excluded.descr <> '' THEN excluded.descr ELSE products.descr END;

-- 5. Sizes and prices — 198 rows.
INSERT INTO variants (product_id, size, price_ngn) VALUES
  ('dewivy-bodymist', '100ml', 7500),
  ('exotic-kiss-bodymist', '100ml', 7500),
  ('goldplum-bodymist', '100ml', 7500),
  ('macho-bodymist', '100ml', 7500),
  ('magicspell-bodymist', '100ml', 7500),
  ('pheromona-bodymist', '100ml', 7500),
  ('sisi-bodymist', '100ml', 7500),
  ('sugar-lips-bodymist', '100ml', 7500),
  ('tango-bodymist', '100ml', 7500),
  ('tlc-bodymist', '100ml', 7500),
  ('toke-bodymist', '100ml', 7500),
  ('body-mist-set-of-11', 'Set', 80000),
  ('body-mist-set-of-6', 'Set', 42000),
  ('2sexy2resist', '30ml', 25000),
  ('a-million-kisses', '50ml', 35000),
  ('after-dark', '30ml', 25000),
  ('bad-character', '30ml', 25000),
  ('bad-character', '50ml', 40000),
  ('bgs02', '50ml', 30000),
  ('boss-babe', '30ml', 25000),
  ('chapter-5', '30ml', 35000),
  ('cleopatra', '30ml', 25000),
  ('dangerous', '50ml', 30000),
  ('dominance', '50ml', 40000),
  ('dynasty', '50ml', 50000),
  ('erotica', '30ml', 25000),
  ('essence-of-love', '30ml', 25000),
  ('flames', '30ml', 30000),
  ('good-girl-carolina', '30ml', 25000),
  ('high-voltage', '30ml', 25000),
  ('intenso', '30ml', 25000),
  ('invictus', '30ml', 25000),
  ('kemistry', '30ml', 25000),
  ('kill-me-softly', '30ml', 30000),
  ('kiss-me-deep', '30ml', 30000),
  ('kiss-me-deep', '50ml', 40000),
  ('lick-me-up', '30ml', 25000),
  ('love-breeze-02', '30ml', 20000),
  ('love-spell', '30ml', 25000),
  ('made-for-romance', '30ml', 25000),
  ('miz-pheromone', '50ml', 55000),
  ('molecule-05', '30ml', 25000),
  ('money-bag', '100ml', 100000),
  ('nutty', '30ml', 25000),
  ('osk-limited', '30ml', 30000),
  ('sauce-queen', '50ml', 45000),
  ('secrets-stilettos', '50ml', 55000),
  ('sweet-sin', '50ml', 30000),
  ('under-his-skin', '30ml', 30000),
  ('very-sexy-you', '50ml', 40000),
  ('assasination-box-1', 'Set', 35000),
  ('assasination-box-2', 'Set', 35000),
  ('dr-teals-coconut', 'One size', 12000),
  ('dr-teals-elderberry', 'One size', 12000),
  ('dr-teals-energy-spray', 'One size', 12500),
  ('dr-teals-eucalyptus', 'One size', 12000),
  ('dr-teals-lavender', 'One size', 12000),
  ('dr-teals-rose-milk', 'One size', 12000),
  ('5th-avenue', '30ml', 25000),
  ('addictive-ambergris', '50ml', 55000),
  ('afternoon-swim', '30ml', 40000),
  ('amouage-decision', '50ml', 50000),
  ('amouage-epicman', '50ml', 40000),
  ('amouage-existence', '50ml', 50000),
  ('amouage-outlands', '50ml', 50000),
  ('amouage-portrayal', '50ml', 40000),
  ('ani-nishane', '50ml', 50000),
  ('baccarat-rogue', '30ml', 30000),
  ('baronda-massamoto', '30ml', 30000),
  ('blue-talisman', '30ml', 30000),
  ('cool-water-women', '30ml', 25000),
  ('couture-oud', '50ml', 40000),
  ('creed-carmina', '30ml', 25000),
  ('decadence', '50ml', 45000),
  ('dior-sauvage', '30ml', 25000),
  ('fahrenheit', '30ml', 50000),
  ('gucci-guilty-men', '30ml', 25000),
  ('gyan', '30ml', 45000),
  ('hibiscus-mahajad', '50ml', 40000),
  ('kutay-unique-luxury', '30ml', 35000),
  ('kutay-unique-luxury', '50ml', 50000),
  ('limelight', '30ml', 30000),
  ('orage-lv', '30ml', 25000),
  ('oud-couture', '30ml', 25000),
  ('oud-ispahan', '30ml', 25000),
  ('oud-maracuja', '50ml', 40000),
  ('oud-satin-mood', '50ml', 50000),
  ('pacific-chill', '50ml', 50000),
  ('rich-leather', '30ml', 25000),
  ('rich-leather', '50ml', 45000),
  ('scandal-jpg', '30ml', 25000),
  ('scandal-jpg', '50ml', 40000),
  ('seminalis-orto-parisi', '50ml', 50000),
  ('si-armani', '30ml', 25000),
  ('sugar-baby', '30ml', 20000),
  ('sugar-leather', '50ml', 50000),
  ('sun-song', '30ml', 25000),
  ('tygar', '30ml', 45000),
  ('vanilla-powder', '50ml', 50000),
  ('2sexy2resist-edp', '30ml', 25000),
  ('b17', '30ml', 25000),
  ('b18', '30ml', 25000),
  ('b21', '30ml', 25000),
  ('b23', '30ml', 25000),
  ('b24', '30ml', 25000),
  ('b25', '30ml', 25000),
  ('b27', '30ml', 25000),
  ('bare-secrets', '30ml', 35000),
  ('bare-skin', '100ml', 55000),
  ('breaking-rules', '100ml', 55000),
  ('honey-trap', '30ml', 30000),
  ('ijele', '50ml', 40000),
  ('lavida-loca', '50ml', 45000),
  ('little-miss-temptation', '30ml', 30000),
  ('lush-life', '50ml', 40000),
  ('mind-games', '30ml', 30000),
  ('opulent-pink-box', 'Set', 25000),
  ('peak-of-passion', '50ml', 40000),
  ('pulze', '30ml', 30000),
  ('raw', '30ml', 30000),
  ('rich-tension', '30ml', 30000),
  ('risky-fire', '100ml', 55000),
  ('secret-flame', '50ml', 30000),
  ('sensuality-burst', '30ml', 25000),
  ('sexy-time', '30ml', 30000),
  ('slow-k-ller', '100ml', 55000),
  ('snatched', '30ml', 25000),
  ('stuck-on-me', '30ml', 30000),
  ('sweet-addiction', '30ml', 25000),
  ('sweet-berry-pop', '50ml', 45000),
  ('sweet-trouble', '100ml', 55000),
  ('terri-3', '10ml', 20000),
  ('terri-3', '100ml', 100000),
  ('the-topic', '100ml', 55000),
  ('vanilla-explosion', '30ml', 30000),
  ('walking-daydream', '30ml', 30000),
  ('wild-by-default', '30ml', 30000),
  ('armpitox', 'One size', 10000),
  ('bikini-booster', '10ml', 10000),
  ('bikini-brightening-cream', 'One size', 10000),
  ('bikini-freshener-mist', '50ml', 10000),
  ('bikini-oil', '50ml', 20000),
  ('bikini-oil-refill', '100ml', 30000),
  ('bikini-package', 'Set', 50000),
  ('bikini-wash', '150ml', 20000),
  ('cranbiotic-gummies', 'One size', 17000),
  ('freshness-gummies', 'One size', 17000),
  ('hello-fresh-pits', '50ml', 12000),
  ('spa-set', 'Set', 10000),
  ('yummy-bikini-oil', '50ml', 20000),
  ('yummy-bikini-wash', '100ml', 20000),
  ('peach-pink-box', 'Set', 50000),
  ('peach-box', 'Set', 25000),
  ('ultimate-queens-package', 'Set', 120000),
  ('back-to-school-kit', 'Set', 30000),
  ('noni-berry-drink', 'One size', 50000),
  ('00-1-diffuser', '150ml', 18000),
  ('00-1-diffuser', '500ml', 55000),
  ('00-1-roomspray', '100ml', 15000),
  ('arabian-oud-roomspray', '100ml', 15000),
  ('bed-of-roses-diffuser', '150ml', 18000),
  ('bed-of-roses-diffuser', '250ml', 20000),
  ('before-sunrise-diffuser', '150ml', 18000),
  ('before-sunrise-roomspray', '100ml', 15000),
  ('blackberry-roomspray', '100ml', 15000),
  ('boozy-diffuser', '150ml', 18000),
  ('bougie-candle', 'One size', 18000),
  ('car-diffuser', 'One size', 5000),
  ('cherry-blossom-diffuser', '150ml', 18000),
  ('cherry-blossom-roomspray', '100ml', 15000),
  ('choco-haven-candle', 'One size', 18000),
  ('citrus-grove-diffuser', '150ml', 18000),
  ('citrus-grove-roomspray', '100ml', 15000),
  ('daisy-diffuser', '150ml', 18000),
  ('daisy-diffuser', '500ml', 55000),
  ('daisy-roomspray', '100ml', 15000),
  ('fresh-dawn-diffuser', '150ml', 18000),
  ('fresh-dawn-diffuser', '500ml', 55000),
  ('fresh-dawn-roomspray', '100ml', 15000),
  ('frozen-mountain-diffuser', '150ml', 18000),
  ('homecoming-diffuser', '150ml', 18000),
  ('laundry-perfume-floral', 'One size', 5000),
  ('laundry-perfume-woody', 'One size', 5000),
  ('naughty-wild-candle', 'One size', 18000),
  ('pine-sky-diffuser', '150ml', 18000),
  ('sacred-space-diffuser', '150ml', 18000),
  ('sacred-space-roomspray', '100ml', 15000),
  ('sips-roomspray', '100ml', 15000),
  ('soft-corner-diffuser', '150ml', 18000),
  ('soft-corner-roomspray', '100ml', 15000),
  ('strawberry-cheesecake-candle', 'One size', 18000),
  ('sweet-berry-diffuser', '150ml', 18000),
  ('tangacitra-candle', 'One size', 18000),
  ('wild-fig-diffuser', '150ml', 18000),
  ('zanga-diffuser', '500ml', 55000),
  ('zingy-diffuser', '150ml', 18000),
  ('massage-oil-sensual', 'One size', 12000),
  ('massage-oil-wild-emotion', 'One size', 12000)
ON CONFLICT(product_id, size) DO UPDATE SET price_ngn = excluded.price_ngn;

-- 6. Opening stock: 10 of every size at each store, and only where the store
--    has no count yet — a real count already entered in the admin is never
--    overwritten.
INSERT INTO stock (variant_id, location_id, qty)
SELECT v.id, l.id, 10 FROM variants v JOIN locations l
WHERE v.product_id IN (
  'dewivy-bodymist', 'exotic-kiss-bodymist', 'goldplum-bodymist', 'macho-bodymist', 
  'magicspell-bodymist', 'pheromona-bodymist', 'sisi-bodymist', 'sugar-lips-bodymist', 
  'tango-bodymist', 'tlc-bodymist', 'toke-bodymist', 'body-mist-set-of-11', 
  'body-mist-set-of-6', '2sexy2resist', 'a-million-kisses', 'after-dark', 'bad-character', 
  'bgs02', 'boss-babe', 'chapter-5', 'cleopatra', 'dangerous', 'dominance', 'dynasty', 
  'erotica', 'essence-of-love', 'flames', 'good-girl-carolina', 'high-voltage', 'intenso', 
  'invictus', 'kemistry', 'kill-me-softly', 'kiss-me-deep', 'lick-me-up', 'love-breeze-02', 
  'love-spell', 'made-for-romance', 'miz-pheromone', 'molecule-05', 'money-bag', 'nutty', 
  'osk-limited', 'sauce-queen', 'secrets-stilettos', 'sweet-sin', 'under-his-skin', 
  'very-sexy-you', 'assasination-box-1', 'assasination-box-2', 'dr-teals-coconut', 
  'dr-teals-elderberry', 'dr-teals-energy-spray', 'dr-teals-eucalyptus', 'dr-teals-lavender', 
  'dr-teals-rose-milk', '5th-avenue', 'addictive-ambergris', 'afternoon-swim', 
  'amouage-decision', 'amouage-epicman', 'amouage-existence', 'amouage-outlands', 
  'amouage-portrayal', 'ani-nishane', 'baccarat-rogue', 'baronda-massamoto', 'blue-talisman', 
  'cool-water-women', 'couture-oud', 'creed-carmina', 'decadence', 'dior-sauvage', 'fahrenheit', 
  'gucci-guilty-men', 'gyan', 'hibiscus-mahajad', 'kutay-unique-luxury', 'limelight', 
  'orage-lv', 'oud-couture', 'oud-ispahan', 'oud-maracuja', 'oud-satin-mood', 'pacific-chill', 
  'rich-leather', 'scandal-jpg', 'seminalis-orto-parisi', 'si-armani', 'sugar-baby', 
  'sugar-leather', 'sun-song', 'tygar', 'vanilla-powder', '2sexy2resist-edp', 'b17', 'b18', 
  'b21', 'b23', 'b24', 'b25', 'b27', 'bare-secrets', 'bare-skin', 'breaking-rules', 
  'honey-trap', 'ijele', 'lavida-loca', 'little-miss-temptation', 'lush-life', 'mind-games', 
  'opulent-pink-box', 'peak-of-passion', 'pulze', 'raw', 'rich-tension', 'risky-fire', 
  'secret-flame', 'sensuality-burst', 'sexy-time', 'slow-k-ller', 'snatched', 'stuck-on-me', 
  'sweet-addiction', 'sweet-berry-pop', 'sweet-trouble', 'terri-3', 'the-topic', 
  'vanilla-explosion', 'walking-daydream', 'wild-by-default', 'armpitox', 'bikini-booster', 
  'bikini-brightening-cream', 'bikini-freshener-mist', 'bikini-oil', 'bikini-oil-refill', 
  'bikini-package', 'bikini-wash', 'cranbiotic-gummies', 'freshness-gummies', 
  'hello-fresh-pits', 'spa-set', 'yummy-bikini-oil', 'yummy-bikini-wash', 'peach-pink-box', 
  'peach-box', 'ultimate-queens-package', 'back-to-school-kit', 'noni-berry-drink', 
  '00-1-diffuser', '00-1-roomspray', 'arabian-oud-roomspray', 'bed-of-roses-diffuser', 
  'before-sunrise-diffuser', 'before-sunrise-roomspray', 'blackberry-roomspray', 
  'boozy-diffuser', 'bougie-candle', 'car-diffuser', 'cherry-blossom-diffuser', 
  'cherry-blossom-roomspray', 'choco-haven-candle', 'citrus-grove-diffuser', 
  'citrus-grove-roomspray', 'daisy-diffuser', 'daisy-roomspray', 'fresh-dawn-diffuser', 
  'fresh-dawn-roomspray', 'frozen-mountain-diffuser', 'homecoming-diffuser', 
  'laundry-perfume-floral', 'laundry-perfume-woody', 'naughty-wild-candle', 'pine-sky-diffuser', 
  'sacred-space-diffuser', 'sacred-space-roomspray', 'sips-roomspray', 'soft-corner-diffuser', 
  'soft-corner-roomspray', 'strawberry-cheesecake-candle', 'sweet-berry-diffuser', 
  'tangacitra-candle', 'wild-fig-diffuser', 'zanga-diffuser', 'zingy-diffuser', 
  'massage-oil-sensual', 'massage-oil-wild-emotion'
)
ON CONFLICT(variant_id, location_id) DO NOTHING;
